// This file is auto-generated by src/utils/icons/generate-icon-map.mjs.
// Do not edit manually. Run "npm run generate:icons" (or node src/utils/icons/generate-icon-map.mjs) to regenerate.

import type { IconType } from 'react-icons';
import { LuArrowRight, LuChartBar, LuChevronRight, LuCode, LuContact, LuGithub, LuGlobe, LuLinkedin, LuMail, LuMegaphone, LuMousePointer, LuPhone, LuSearch, LuThumbsUp, LuTwitter } from 'react-icons/lu';
import { FaBullhorn, FaCode } from 'react-icons/fa';
import { SiFacebook } from 'react-icons/si';

export const iconMap = {
  'fa:bullhorn': FaBullhorn,
  'fa:code': FaCode,
  'lu:arrow-right': LuArrowRight,
  'lu:chart-bar': LuChartBar,
  'lu:chevron-right': LuChevronRight,
  'lu:code': LuCode,
  'lu:contact': LuContact,
  'lu:github': LuGithub,
  'lu:globe': LuGlobe,
  'lu:linkedin': LuLinkedin,
  'lu:mail': LuMail,
  'lu:megaphone': LuMegaphone,
  'lu:mouse-pointer': LuMousePointer,
  'lu:phone': LuPhone,
  'lu:search': LuSearch,
  'lu:thumbs-up': LuThumbsUp,
  'lu:twitter': LuTwitter,
  'si:facebook': SiFacebook,
} satisfies Record<string, IconType>;

export type IconKey = keyof typeof iconMap;
